### GET PROCESSES
GET https://testbed.dev.52north.org/eopad/rest/processes/
Accept: application/json

### CREATE NDVI
POST https://testbed.dev.52north.org/eopad/rest/processes/
Content-Type: application/json

< ndvi/application-package.json

### CREATE QUALITY
POST https://testbed.dev.52north.org/eopad/rest/processes/
Content-Type: application/json

< quality/application-package.json

### GET NDVI
GET https://testbed.dev.52north.org/eopad/rest/processes/org.n52.project.tb15.eopad.NdviCalculation
Accept: application/json

### GET QUALITY
GET https://testbed.dev.52north.org/eopad/rest/processes/org.n52.project.tb15.eopad.SentinelQualityAreaOfInterest
Accept: application/json


### EXECUTE QUALITY
POST https://testbed.dev.52north.org/eopad/rest/processes/org.n52.project.tb15.eopad.SentinelQualityAreaOfInterest/jobs
Accept: application/json
Content-Type: application/json

{
  "inputs": [
    {
      "id": "source",
      "input": {
        "format": { "mimeType": "text/plain" },
        "value": {
          "inlineValue": "S2B_MSIL1C_20190614T103029_N0207_R108_T32ULC_20190614T124423"
        }
      }
    },
    {
      "id": "areaOfInterest",
      "input": {
        "format": { "mimeType": "application/geo+json" },
        "value": {
          "inlineValue": {
            "type": "Polygon",
            "coordinates": [
              [
                [7.1726426, 51.7542339],
                [7.1532584, 51.7517],
                [7.1596957, 51.7424401],
                [7.1596957, 51.7424401],
                [7.1770033, 51.7352082],
                [7.1770033, 51.7352082],
                [7.2216706, 51.7297689],
                [7.2194428, 51.7550836],
                [7.1726426, 51.7542339]
              ]
            ]
          }
        }
      }
    }
  ],
  "outputs": [
    {
      "id": "cloudCoverage",
      "transmissionMode": "value",
      "format": { "mimeType": "text/plain" }
    }
  ]
}

### EXECUTE NDVI
POST https://testbed.dev.52north.org/eopad/rest/processes/org.n52.project.tb15.eopad.NdviCalculation/jobs
Accept: application/json
Content-Type: application/json

{
  "inputs":[
    {
      "id": "source",
      "input": { 
        "format": { "mimeType": "text/plain" },
        "value": { 
          "inlineValue": "S2B_MSIL1C_20190614T103029_N0207_R108_T32ULC_20190614T124423"
        }
      }
    },
    {
      "id": "nir_factor",
      "input": { "value": 1.0 }
    },
    {
      "id": "red_factor",
      "input": { "value": 1.0 }
    }
  ],
  "outputs": [
    {
      "id": "raster",
      "format": { "mimeType": "image/geotiff" },
      "transmissionMode": "reference"
    }
  ]
}

###
GET https://testbed.dev.52north.org/eopad/rest/processes/org.n52.project.tb15.eopad.NdviCalculation/jobs
Accept: application/json


### UPDATE NDVI
PUT https://testbed.dev.52north.org/eopad/rest/processes/org.n52.project.tb15.eopad.NdviCalculation
Content-Type: application/json

< ndvi/application-package.json

### UPDATE QUALITY
PUT https://testbed.dev.52north.org/eopad/rest/processes/org.n52.project.tb15.eopad.SentinelQualityAreaOfInterest
Content-Type: application/json

< quality/application-package.json

### DELETE NDVI
DELETE https://testbed.dev.52north.org/eopad/rest/processes/org.n52.project.tb15.eopad.NdviCalculation

### DELETE QUALITY
DELETE https://testbed.dev.52north.org/eopad/rest/processes/org.n52.project.tb15.eopad.SentinelQualityAreaOfInterest

### GET GMU/SERVICE
GET https://cloud.csiss.gmu.edu/ows15/geonet/rest3a/ogc/cat3a/services/org.52north.dev.testbed.eopad.rest
Accept: application/geo+json
Authorization: Basic Y2F1dGVybWFubjpZQ1V4SEY0Zw==

### GET GMU/NDVI
GET https://cloud.csiss.gmu.edu/ows15/geonet/rest3a/ogc/cat3a/services/org.n52.project.tb15.eopad.NdviCalculation
Accept: application/geo+json
Authorization: Basic Y2F1dGVybWFubjpZQ1V4SEY0Zw==

### GET GMU/NDVI
GET https://cloud.csiss.gmu.edu/ows15/geonet/rest3a/ogc/cat3a/services/org.n52.project.tb15.eopad.SentinelQualityAreaOfInterest
Accept: application/geo+json
Authorization: Basic Y2F1dGVybWFubjpZQ1V4SEY0Zw==


### GET DEIMOS/SERVICE
GET http://servicecatalogue-ogctestbed15.deimos.pt/smi/services/org.52north.dev.testbed.eopad.rest
Accept: application/geo+json

### GET GMU/NDVI
GET http://servicecatalogue-ogctestbed15.deimos.pt/smi/services/org.n52.project.tb15.eopad.NdviCalculation
Accept: application/geo+json

### GET GMU/NDVI
GET http://servicecatalogue-ogctestbed15.deimos.pt/smi/services/org.n52.project.tb15.eopad.SentinelQualityAreaOfInterest
Accept: application/geo+json

### Get status
GET https://testbed.dev.52north.org/eopad/rest/processes/org.n52.project.tb15.eopad.NdviCalculation/jobs/06d38f16-82c5-4b13-8156-237243c69a97
### Get result
GET https://testbed.dev.52north.org/eopad/rest/processes/org.n52.project.tb15.eopad.NdviCalculation/jobs/06d38f16-82c5-4b13-8156-237243c69a97/result/raster